#bitwaise opertor on True and Flase 
print(True ^ False)
print(False ^ False)
print(False ^ True)
print(True ^ True)
print()
print(True & False)
print(False & True)
print(True & True)
print(False & False)
print()
print(True | False)
print(False | True)
print(True | True)
print(False | False)